paths:
  /api/products:
    get:
      summary: Get all products
      description: Retrieves all available products.
      responses:
        '200':
          description: List of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      description: Creates a new product in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully.
  /api/products/{id}:
    get:
      summary: Get a product by ID
      description: Retrieves a product by its ID.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the product to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Data of the requested product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      summary: Update a product by ID
      description: Updates an existing product by its ID.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the product to update.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product updated successfully.
    delete:
      summary: Delete a product by ID
      description: Deletes an existing product by its ID.
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the product to delete.
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully.
components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Title of the product.
        description:
          type: string
          description: Description of the product.
        code:
          type: string
          description: Product code.
        price:
          type: number
          description: Price of the product.
        stock:
          type: number
          description: Available stock of the product.
        category:
          type: string
          description: Category of the product.
      required:
        - title
        - description
        - code
        - price
        - stock
        - category
